FROM docker.io/library/nginx:latest

RUN mkdir -p /etc/nginx/conf.d/
COPY default.conf /etc/nginx/conf.d/default.conf
COPY update_nginx.sh /tools/update_nginx.sh
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]